package:
  name: llvmpy
  version: 99.9.9

source:
  git_url: git@github.com:llvmpy/llvmpy.git
#  git_tag: 0.12.0

requirements:
  build:
    - llvm
    - python
    #- chrpath        [linux]
  run:
    - llvm           [unix]
    - python

test:
  requires:
    - unittest2      [py26]
  imports:
    - llvm
    - llvmpy
    - llvmpy._api
    - llvmpy._capsule
    - llpython
    - llvm_array
    - llvm_cbuilder


